import Component from '@ember/component';
import { computed } from '@ember/object';

const messages = [
  { username: 'ABA', message: "Le meilleur \"grumpy developer\" que je connaisse. J'ai adoré nos échanges lors de pause-cigarette-électronique au bord du stade. Tu vas trop me manquer." },
  { username: 'ABN', message: "Je t'ai connu alternant RH, développeur reconverti, auteur d'un article sur les animations CSS de grande classe et maintenant manager ! Wahou, que de chemin parcouru. Continues comme ça et tu vas vite tous nous dépasser. Même FHI ! ;-)" },
  { username: 'ABU', message: "Bon courage pour la traduction et l'update des GdW. PS : trop la classe d'avoir LCI en manager ^^" },
  { username: 'ACH', message: "Le mec le plus Rock'n Roll de tout OCTO. Une personne de confiance et une source d'inspiration pour le petit leader de tribu que je suis." },
  { username: 'AFA', message: "Pour moi tu resteras toujours comme le frère de Christian, avec qui j'ai aimé les quelques cafés qu'on a partagés ensemble." },
  { username: 'AGA', message: "J'aime beaucoup ta tête sur AskBob" },
  { username: 'AGR', message: "Au nom de la tribu WEBF, désolé de n'avoir pas encore rempli le questionnaire sur le changement de tribu ^^" },
  { username: 'AHU', message: "Ma référence parmi les leaders de tribu. T'es une super personne et toujours de bon conseil. CRAFT a de la chance de t'avoir en tant que leader." },
  { username: 'AJU', message: "Je suis fier d'avoir été ton manager durant cette année et d'avoir discuté bébé lors de nos O3. Bon courage pour trouver la nounou ou la crèche de tes rêves. Vivement que tu passes consultant confirmé, pour que j'arrête de me tromper ;-)" },
  { username: 'ALB', message: "Si tes talents de consultant sont aussi développés que tes compétences au babyfoot, alors on tient une perle ^^" },
  { username: 'AMO', message: "Bonne chance pour la fin de ton stage :-)" },
  { username: 'AMS', message: "Le dernier développeur iOS d'OCTO. Ou pas. j'ai apprécié partager des parties de baby, des cafés et des déjeuners avec toi. Bisous" },
  { username: 'AMZ', message: "Que pourrais-je dire qui n'a déjà été dit sur LE Arnaud Mazin. Trop fier d'avoir passé 1/2 journée avec toi, à apprendre Ansible. Pour info, on l'utilise encore sur Pix. #IWorkedWithAMZ" },
  { username: 'ANB', message: "J'espère que les copains de Pix t'ont bien accueilli et que tu as vu ce que tu voulais voir ^^" },
  { username: 'ANV', message: "À toi aussi elle t'a servi les formations \"parler en public\" & cie. ? Bisous." },
  { username: 'AOZ', message: "T'as finalement réussi à installer un dual-boot sur ta machine ? ;-p" },
  { username: 'API', message: "Le mec qui pèse. Dommage que ça n'ait pas donné plus Hachette." },
  { username: 'ARA', message: "Je garde en tête ce que tu as fait sur CNP et le trophée que l'équipe a obtenu grâce à vous." },
  { username: 'ARB', message: "Excellent ton article sur WebAssembly ! Et la discussion sur HackerNews... Bravo !" },
  { username: 'ARD', message: "Je ne désespère pas de travailler avec toi un de ces jours ;-)" },
  { username: 'ARN', message: "On n'aura pas eu le temps de bosser ensemble, mais de nos quelques échanges dans l'ascenseur ou au café, t'as l'air hyper cool. #unjourpeutetre" },
  { username: 'ARP', message: "Viens chez WEBF et tu verras que le développement Web, ce n'est pas qu'un truc de stagiaire !" },
  { username: 'ARS', message: "J'espère que ta nouvelle mission se passe comme tu veux. Bisous" },
  { username: 'ASA', message: "Le mec le plus \"accessible\" d'OCTO. Je suis trop fier de t'avoir le premier accordé officiellement le titre de Tech Lead. Content de te retrouver demain." },
  { username: 'AUB', message: "Coucou ! Je t'aurais bien vu chez WEBF. Un jour peut-être ;-)" },
  { username: 'AUG', message: "Merci pour ton aide pour sizer et gérer la nouvelle infra de Pix sur OVH. Pour info, ça tourne nickel !" },
  { username: 'AWI', message: "Garde ta bonne humeur de tous les jours, elle esrt contagieuse :-D" },
  { username: 'BBR', message: "J'entends que du bien du projet GRTGaz. Il paraît que tu y es pour beaucoup. C'est cool. Dommage qu'on ait pas eu l'occasion de travailler ensemble. ++" },
  { username: 'BEJ', message: "Que de chemin parcouru depuis la SKOOL ! On peut dire que \"tu as bien grandi\" :-p" },
  { username: 'BHA', message: "Le meilleur DAF que j'ai pu croiser (en 5 entreprises). Tes rapports sont toujours au poil, à l'heure et avec bonne humeur. OCTO a de la chance de t'avoir. Bisous." },
  { username: 'BIS', message: "Merci pour ton sourire et pour ton aide à chaque fois que j'ai galéré. Bonne chance pour tes prochaines compétitions. #BIS #numberOne #champion" },
  { username: 'BJC', message: "L'un de mes parrainés. Je retiendrai toute ma vie ta présentation épique lors d'une pleinière y a longtemps X-D Bisous et bonne chance pour la suite !" },
  { username: 'BLA', message: "Trop de choses me viennent en tête. Je suis fier d'avoir été ton managé. Tu m'as bien aidé à grandir et endosser le costume de leader de tribu, en me posant les bonnes questions, en me donnant les bons conseils et en me challengeant avec pertinence. Désormais je vais voler de mes propres ailes. Tu resteras l'un de mes modèles. Bonne chance pour la suite des tribus. Bonne chance aussi avec ton équipe de hand. PS : J'aurais tellement dû t'écouter et investir dans le BitCoin ! #amitiés" },
  { username: 'BLJ', message: "Dispo pour parler de Pix et évoquer un partenariat avec OCTO quand tu veux :-)" },
  { username: 'BMO', message: "Merci pour ta bonne humeur et ton aide à chaque fois que j'ai eu des soucis d'admin. Bisous ;-)" },
  { username: 'BOA', message: "La plus belle tignasse de tout OCTO. Bravo !" },
  { username: 'BRM', message: "Non ! Ce trigramme n'existe définitivement pas dans cet univers." },
  { username: 'BRO', message: "J'espère que t'as bien profité de ta partie de \"vrai\" baby remportée tout à l'heure. Je t'attends au laser game, sur FIFA et au mini-baby ! #revengeSpirit #ChampionsProject" },
  { username: 'BTA', message: "J'espère que tu ne regrettes pas ta vie d'interne d'avant et que tu continues de t'éclater chez OCTO :-)" },
  { username: 'BTI', message: "Le sosie de Mark Zuckerberg. Je te souhaite la même réussite." },
  { username: 'BTO', message: "Pour moi, tu es celui qui symbolise le plus l'Esprit OCTO et ses valeurs. C'est tellement toujours un plaisir de discuter avec toi. Et ce que tu fais avec la DuckConf." },
  { username: 'CAB', message: "Je ne sais pas si OCTO se rend compte de t'avoir et de tout ce que tu fais pour nous, notre image etc. En tout cas, la plupart des Octos que je connais et moi, si. Continues à tout déchirer. Bisous." },
  { username: 'CAM', message: "Tes créations sont des tueries qui permettent à OCTO de briller en plus de rayonner. C'est trop cool." },
  { username: 'CBR', message: "J'attends toujours un nouveau logo pour WEBF !!! PS : j'ai une pensée émue et compatissante à tous tes futurs adversaires au babyfoot que tu vas démolir avec ton coup de poignet dévastateur ^^" },
  { username: 'CCI', message: "Je trouve ta photo de profil sur AskBob un peu tristouille. À part ça, t'as l'air cool (c'est ton col-en-V qui me fait dire ça ^^)" },
  { username: 'CCO', message: "J'espère que tu kiffes sur Appaloosa. Au pire, WEBF te tend les bras ;-)" },
  { username: 'CDP', message: "\"L'enfant indésiré\" sur La Poste... tu t'en es sorti comme si de rien n'était, malgré que ce fut ta première mission OCTO. #impressionnant PS : je ne sais pas si on te l'a déjà dit, mais ta photo sur AskBob fait un peu \"tueur psychopathe\" X-D "},
  { username: 'CDR', message: "Cyrille, je garderai beaucoup d'estime pour toi. Tu m'as fait grandir comme peu de personne chez OCTO. On a parfois eu du mal à se comprendre, mais ça ne m'empêche pas de vraiment apprécier nos échanges. Je te souhaite tout le meilleur pour la suite et encore plus de confs mouf-mouf comme tu sais si bien les faire. #monPremierDeMa #TheRealPrinceCharmant" },
  { username: 'CDS', message: "Tu ne le sais pas encore mais j'ai une place réservée à ton nom sur Pix en 2018. D'ici là, continue de déchirer sur tes missions comme je l'entends si souvent. ++" },
  { username: 'CDU', message: "Il paraît que tu as fait des miracles avec Airtable. Heureux (et fier) de t'avoir fait découvrir l'outil (du coup, merci TWI qui me l'a montré le premier). Bonne continuation pour la suite." },
  { username: 'CEM', message: "Pour le peu qu'on s'est croisé sur EISMO, t'es un mec cool. PS : je trouve que t'as un petit côté ABA qui te va bien ^^" },
  { username: 'CFA', message: "Le philosophe à l'accent qui chante d'OCTO. J'ai adoré discuter avec toi et encore plus t'écouter. C'est toujours passionnant et enrichissant." },
  { username: 'CFI', message: "Difficile de prendre la relève de Pauline dans le coeur des Octos, et pourtant tu l'as fait de main de maître ! OCTO a vraiment de la chance de t'avoir. Comme toute la team RH. C'était trop cool de travailler avec toi. Bisous." },
  { username: 'CGI', message: "J'aurais tellement aimé t'avoir sur Pix prochainement." },
  { username: 'CGR', message: "Comme je t'ai déjà dit, j'ai trop de regret qu'on n'ait pas pu travailler ensemble plus et avant. T'es une super belle personne et les consultants qui travailleront avec toi ou sur tes missions auront bien de la chance :-)" },
  { username: 'CHA', message: "J'ai entendu dire que tu as des talents de danseur hors pair. S'ils sont à la mesure de tes talents de Javaiste, y a du niveau. #TeamBA" },
  { username: 'CHL'	, message: 	"J'ai bien aimé me voir remettre ma lettre de départ de ta main. Désolé pour mon entrée en matière chelou. Je te souhaite de t'éclater chez OCTO. Bisous "},
  { username: 'CLB', message: "Bon courage et bonne chance pour vendre du OCAC. C'est un super produit, avec un super catalogue et tu es un super IA. Tout est réuni :-)" },
  { username: 'CLD', message: "Pour moi, et même si le Klub Sosie a refusé ma proposition, tu resteras à jamais le clone de Damon Salvatore dans Vampire Diaries : http://fr.vampirediaries.wikia.com/wiki/Damon_Salvatore Bon ; d'ici à ce que tout le monde se range à mon avis, je te souhaite un maxi co-leading de la tribu avec Pierrette et Xavier ;-)" },
  { username: 'CLI', message: "Pour moi tu resteras un ninja : discret mais efficace. Bonne continuation :-)" },
  { username: 'CQU', message: "Je suis trop content de t'avoir sur Pix. On avait de la \"dette d'un mec qui porte une queue de cheval\" depuis le départ de Pierre (de la Morinerie). Maintenant, tout va aller mieux ;-)" },
  { username: 'CRI', message: "C'est une vraie fierté de t'avoir recruté, pour OCTO, pour WEBF et personnellement. Tu vas tout déchirer dans les prochains mois et années. Je vais beaucoup regretter de ne pas pouvoir être là pour voir ça et t'aider à grandir à ta mesure. Mais j'ai toute confiance en Pierrette pour prendre la relève encore mieux que je ne l'aurais fait ^^" },
  { username: 'CRU', message: "Les luthiers proche des Champs et maintenant d'Opéra te remercient d'avoir autant initié et démocratisé le yukulélé sur les projets informatiques, de Boulogne à Saint-Denis. :-D" },
  { username: 'CTH', message: "Merci d'avoir le courage de partager tes réflexions avec nous. C'est toujours intéressant et ça fait réfléchir. C'est pas toujours facile, mais ça fait toujours du bien ^^" },
  { username: 'CYD', message: "Non !" },
  { username: 'CYG', message: "Le rugby, non. Le foot, oui :-D" },
  { username: 'DAB', message: "Maître Beaufils a.k.a. le Bien-Monté a.k.a. le Tech Lead attitré de la FFT / Roland-Garros. J'ai trop kiffé travailler ensemble. J'aurais toujours un oeil sur toi. #valpolicella #islande #craft #theRealTLOnTicketsDotRG" },
  { username: 'DAL', message: "Bravo pour avoir lancé OCTO Australie et l'avoir mené aussi loin aussi vite. Je finirai bien par te battre au tennis de table un jour dans le turfu. ;-)" },
  { username: 'DAM', message: "Coucou ! Merci pour ta bonne humeur et ta présence lumineuse les après-midis. À bientôt ;-)" },
  { username: 'DAT', message: "L'un des Papas pour les Octos. La boss du conseil pour beaucoup. Une référence pour tous. C'était un honneur d'être l'un de tes collègues. Mon seul regret : ne pas avoir fait de missions avec toi et appris à tes côtés. Bonne continuation." },
  { username: 'DJO', message: "Merci pour tout ce que tu as apporté à OCTO depuis tant d'années. Merci aussi pour avoir pris du temps avec moi et m'avoir écouté à mes débuts au SGMAP. Quand je te disais que le risque de l'incubateur c'était de voir partir ses talents... ;-) Bonne continuation pour la suite." },
  { username: 'DLE', message: "J'ai eu la chance de travailler avec toi. C'était cool. T'es une super personne. Bienveillant et humble. Merci. #SéminaireAgile #CoachingTF1 #BBLProductManagement" },
  { username: 'DOM', message: "Il faudrait plus qu'une application Web et plusieurs méga de données pour te dire tout le bien que je pense de toi. Tu m'as tellement apporté, appris et fais grandir. Parfois ce fut dur (le prix de l'apprentissage de : la frustration, la patience, l'humilité et l'écoute [entre autres]). Et d'autres beaucoup plus plaisantes. Tu as cru en moi quand même moi j'avais lâché l'affaire. Avec toi, OCTO tient une personne en or. En vrai, je ne peux rien dire de plus précis et complet que : \"MERCI !\" #CNPGranit #FormationSkool #JobBoard #TribeLeading" },
  { username: 'DUJ', message: "Bon courage pour le lead de la tribu UX. Je te souhaite de t'épanouir autant que j'en ai eu la chance :-)" },
  { username: 'EBE', message: "Salut Juju. On n'a pas eu l'occasion de travailler ensemble, mais chaque fois qu'on a discuté, j'ai bien appris et kiffé. Bonne continuation. #RememberAu50 #YetAnotherOCTOLegend" },
  { username: 'EBI', message: "L'une des personnes les plus drôles d'OCTO, mais pas que. Pour l'anecdote, ma belle-mère travaille chez Allianz et elle a assisté à ta présentation récemment dans le cadre des mini-USI. Elle a vraiment beaucoup apprécié ! A part ça, je n'oublierais jamais les WEO qu'on a fait ensemble. Avec ACL, c'était un spectacle à tous les coups. Le voisins de bus idéal ;-)" },
  { username: 'EDE', message: "J'ai beaucoup de respect pour toi. À chaque fois je suis impressionné par ta posture de conseil, la sérénité que tu dégages et qui est contagieuse, et par la qualité de ton expression autant que celle de tes propos. Big up !" },
  { username: 'EFR', message: "MOP killer. Avec toi, le game de la MOP est perdu d'avance. Tu n'en oublies pas de dépanner les copains en mal d'Ops et qui demande de l'aide. Chapeau bas. Avec toi dans les rangs d'OCTO, Accenture n'a qu'à bien se tenir ^^." },
  { username: 'EJA', message: "Le mec qui considère que tous les jeunes et les femmes sont des chauffards." },
  { username: 'ELD', message: "Jusqu'à présent on s'est loupé sur Pix, mais je ne désespère pas. Chapeau pour tout ce que tu (as) fait sur Service-Public.fr. À l'un de ces jours ;-)" },
  { username: 'EMC', message: "J'ai apprécié nos échanges, en particulier au baby. Bravo pour GRTGaz, ça semble être une super mission et les Octos ont vraiment l'air de kiffer. Bonne chane pour la suite." },
  { username: 'EMI', message: "Le sosie non officiel (car rejeté par ce maudit Gang des Sosies) de Marina Kaye. J'ai apprécié chacun de nos échanges et j'ai aimé la pertinence des profils que tu m'as présentés. Bonne continuation. ;-)" },
  { username: 'ERL', message: "Merci d'avoir pensé à moi pour les Startups d'Etat. Pour la confidence, j'ai songé plusieurs fois à quitter la mission, en particulier à la même époque l'année dernière. Je ne regrette absolument pas aujourd'hui d'avoir lutté et de m'être accroché. Merci aussi pour ton aide quant à sortir proprement et rapidement XJU de TPS. Je ne doute pas qu'on sera amené régulièrement à se revoir ^^" },
  { username: 'EST', message: "Tu es l'incarnation qu'une reconversion est possible à tout âge. Et que Simplon ça marche (merci OCTO). Bonne continuation sur Europ Assistance." },
  { username: 'ETO', message: "Un maxi big up à ton travail et ton implication ces derniers temps sur le Job Board. J'espère que tu n'as pas trop pesté contre \"l'ancien propriétaire du code\" ;-)" },
  { username: 'ETR', message: "Gardes ton énergie et ta curiosité, c'est rafraîchissant. Bonne continuation et à une prochaine." },
  { username: 'FAR', message: "J'ai laissé sa chance au hasard au Sénégal (c'était bien le Sénégal ou le Maroc ?) et je ne regrette absolument pas. T'es un super consultant et un super collègue. Et Slide Search, ça marche du tonnerre. PS : Toi aussi ta photo de profil sur AskBob fait flipper." },
  { username: 'FAV', message: "Du peu qu'on s'est croisé sur RMW, tu envoyais du lourd. À la prochaine !" },
  { username: 'FLO', message: "Le mot magique est \"hippopotomonstrosesquippedaliophobie\". Dis-le moi d'une traite et t'auras le droit à 1 voeu ;-)" },
  { username: 'FCE', message: "Tu ne dois pas être très loin de la personne qui a eu l'entretien manager le plus court (moins de 20mn). La seule chose que je regrette c'est que tu aies choisi WOAPI que WEBF au moment fatidique. À part ça, j'ai adoré t'avoir sur Pix. Merci d'avoir accepté de jouer les prolongations pour la certif. J'espère t'avoir fait grandir autant que kiffer. Ah et tu ne le sais pas encore, mais tu me dois un 360. ;-)" },
  { username: 'FDE', message: "C'était cool de t'avoir sur WEBF. J'espère que tu t'éclates encore plus chez CRAFT et que tu continues de distiller tes remarques pertinentes dont toi seul a le secret." },
  { username: 'FHI', message: "Le jour où tu m'as le plus impressionné, c'est une semaine après mon arrivée, alors qu'on se croisait pour la première fois, je t'ai adressé un simple \"Bonjour\" que tu m'as retourné d'un \"Salut, Jérémy\" qui m'a marqué et qui pour moi résume tout l'esprit OCTO (en vrai, j'avoue, sur le moment je me suis vraiment senti con et j'ai pris une grosse claque). Depuis 5 ans que je suis chez OCTO (et même avant) je suis admiratif de cette boîte que tu as montée et des gens – tous plus oufs les uns que les autres – que tu as convaincu de prendre part à l'aventure. Ça m'a vraiment fait mal le jour où on a apprit le rapprochement avec AXE, mais je te fais confiance pour avoir une fois encore raison avant les autres et surtout pour faire en sorte que ça profite à tous les Octos. Bref, tout ça pour dire, bravo et merci François. Bonne chance pour la suite ;-)" },
  { username: 'FJA', message: "Un poto de promo. Mec, t'es une brute. Un commiter Node.js / Mocha en chair et en os, à mes côtés. Trop la classe ! J'aurais vraiment adoré faire une mission ensemble. #2013 #Ember.js" },
  { username: 'FLM', message: "Je te souhaite le meilleur du meilleur pour tes projets." },
  { username: 'FMI', message: "Tu es l'un des meilleurs binômes et copain-dev dont on puisse rêver. Une valeur sûre. #DetuscheKalitat #CNPGranit #CNPWeb #RMW" },
  { username: 'FRA', message: "Merci pour le coup de main sur la formation JS pour la Skool." },
  { username: 'FRC', message: "Bon courage et bonne chance pour ton application de maraude. C'est une super idée et surtout hyper utile pour les gens. Bisous." },
  { username: 'FRD', message: "Toujours un plaisir de papoter avec toi. Bonne continuation." },
  { username: 'FRP', message: "Merci d'avoir permis que TWI revienne sur Pix. Bonne route ;-)" },
  { username: 'FVA', message: "Ah mon petit Flo ! Je n'oublierais jamais notre merveilleuse mission de conseil pour F******o. Je ne sais pas si on s'en est bien sorti, mais au moins on s'en est sorti vivant :-) Au pasage merci MBO. #YAPasQueDesGentils #YAAussiDesTordus" },
  { username: 'FXB', message: "Merci pour tout ce que tu m'as appris et nos échanges richissimes au cours des missions que j'ai eues l'honneur de partager avec toi (Club Med, CNP, CAC&P)" },
  { username: 'FXV', message: "Une pensée émue pour les quelques formations que nous avons partagées. Sans oublier une partie de foot mémorable loin de la France. Bon vent." },
  { username: 'GAD', message: "Mec, t'es une perle. Aussi bienveillant et positif que fort techniquement. Tu déchires. Et finalement, les les exercices Node School pour la formation JS c'était une excellente idée. Bisous" },
  { username: 'GCA', message: "Gardes ton énergie et ta curiosité, c'est rafraîchissant. Bonne continuation et à une prochaine." },
  { username: 'GDS', message: "La France et le Service Public te remercient. Je te kiffe trop. C'était trop bien de travailler avec toi sur SwissLife. Dommage qu'on n'ait pas eu plus de missions ensemble. Je n'oublie pas non pus le temps du 50 et toutes nos petites discussions au 5ème. Gros bisous" },
  { username: 'GUE', message: "J'aurais trop aimé que tu rejoignes WEBF. J'epsère que tu t'éclates chez WOAPI. Bonne continuation." },
  { username: 'GUI', message: "J'ai été fier d'être ton manager cette année. J'espère que tes projets de création de tribu aboutiront. Tu m'impressionnes à chaque fois qu'on parle des courses que tu as faites ou que tu comptes faire. Bravo. @+" },
  { username: 'GUL', message: "Bonne chance et longue vie à la tribu SQUID !" },
  { username: 'HDE', message: "❤" },
  { username: 'HVA', message: "J'ai vraiment apprécié travailler avec toi sur la billetterie de Roland-Garos. Moi de jouer contre toi au baby. Tu m'as appris et montré des trucs qui continuent de m'inspirer, ex : faire confiance à son équipe et à ses choix techniques, même à l'approche d'une deadline très forte ; ou encore, l'importance du cadrage en terme de mise en place d'une dynamique d'équipe. Bisous" },
  { username: 'IAN', message: "T'es une figure historique d'OCTO, et j'ai énormément de respect pour toi. Les Octos (et les clients) qui te côtoient ont énormément de chance. J'espère qu'on se recroisera. ++" },
  { username: 'ILE', message: "CYD a tout dit sur toi. Merci pour tout ce que tu fais pour OCTO, c'est énorme !" },
  { username: 'IPA', message: "Comme Elsa, j'espère que tu n'as pas trop souffert sur le JobBoard. Encore pardon pour mon entrée en matière l'autre fois. Je suis parfois un peu maladroit dans mon exigeance. J'espère que tu vas t'éclater dans tes prochaines missions. Ciao. PS : si ton manager t'embête, dis-moi et je m'en occupe ;-)" },
  { username: 'JAF', message: "J'aurais bien été voir un match au Parc avec toi. Je suis sûr que j'aurais adoré travailler avec toi. Et qu'on aurait tout déchiré. Je te souhaite le meilleur. Bisous. #AllezParis" },
  { username: 'JBR', message: "Je suis fan de ton prénom. Bisous #TeamJérémy" },
  { username: 'JBU', message: "Mais dans quoi tu t'es lancé !?!" },
  { username: 'JDB', message: "Je suis obligé de te présenter mes excuses pour tous les soucis que je t'ai procuré sur ClubMed. Promis, c'était pour le bien d'OCTO et des Octos. Je te souhaite de trouver prochainement un remplaçant à Clément ;-) Gros bisous JD" },
  { username: 'JDO', message: "Oh put*** ! C'est Abel ton manager. Dis-toi que le mec est une arnarque, cf. le petit mot que je lui ai adressé. J'espère que tu vas t'amuser et progresser comme tu veux chez OCTO. ++" },
  { username: 'JDU', message: "J'espère que la formation JS n'a pas été trop rude et que j'ai été un formateur un minimum intéressant. Bonne continuation pour la suite." },
  { username: 'JEA', message: "C'est à chaque fois un plaisir de bosser avec toi. T'as toujours la patate, ça fait plaisir. J'espère avec le plaisir de te recroiser un de ces quatre. Bonne chance pour la suite. #avv #hachette #jobboard #TeamJérémy" },
  { username: 'JEM', message: "Je suis fan de ton prénom. Bisous #TeamJérémy" },
  { username: 'JER', message: "Je suis fan de ton prénom. Bisous #TeamJérémy" },
  { username: 'JJA', message: "J'ai pris tellement cher en débarquant à OCTO sur Octopod avec toi. Je te jure, ça m'a mis la pression direct. Et chaque fois que je pense à toi, je retrouve mon syndrôme de l'imposteur. Et pourtant je sais que t'es un mec en diamant. OCTO, la Skool et Lille ont vraiment beaucoup de chance de t'avoir." },
  { username: 'JLU', message: "J'espère que tu danses bien." },
  { username: 'JOB', message: "Chaque fois que je te vois t'as la patate, c'est contagieux. T'es une fille trop cool. Change pas. Bisous" },
  { username: 'JOT', message: "Je me rappelle d'une discussion, en allant chercher des pizzas au 50 à ton arrivée. C'était cool. Je trouve impressionnant ce que tu as fait sur Appaloosa. Bonne continuation." },
  { username: 'JPE', message: "Ça aurait été tellement cool de t'avoir chez WEBF. Je te souhaite le meilleur chez CRAFT et dans le futur." },
  { username: 'JTE', message: "Si ABA a la palme du Grumpy Developer, toi tu mérites haut la main celle de Budha Developer. Le mec le plus Zen du monde. Ta montée en compétence et ton niveau sur la Billetterie de Roland-Garos m'ont impressionné. Et ton record co-détenu avec Maestre Decourt (3 grosses pizzas en 1 repas !) encore plus. Maxi bissous" },
  { username: 'JUK', message: "L'inventeur de la Duck Conf. #respectMaximum Sans compter la quantité incroyable d'articles de qualité. Si seulement j'avais seulement 1% de tes capacités de rédaction..." },
  { username: 'JUP', message: "Salut Jupette ! Un énorme MERCI pour toutes les fois où tu m'as aidé avec la paperasserie obligatoire. J'espère que ta maternité avec le petit Alek se passe à merveille. Bisous." },
  { username: 'JVI', message: "Cher maître JVI, je vais beaucoup te regretter et nos conversations impromptues, toujours passionnates. Continues de proposer des bières et de faire parler les gens, tu sais si bien le faire. Ah et penses aussi à faire taire la petite voix en toi qui cherche à te diminuer. T'es l'un des Octos avec qui j'aurais le plus voulu travailler. À la prochaine." },
  { username: 'JWA', message: "Quand je pense à toi au Club MEd, je pense à Dieu, dont tout le monde loue les miracles mais qu'on ne voit jamais de ses propres yeux. ;-P Penses à passer à Opéra de temps en temps. PS : je crois que l'équipe Admin a quelque chose pour toi depuis 1 an." },
  { username: 'KEV', message: "L'un des heureux élus avec un trigramme trop classe (cf. DOM, MEL, YOU, etc.). On n'aura donc pas le temps de se refaire un five d'ici mon départ. Pas grave, c'était cool. A+" },
  { username: 'KSZ', message: "Entre nous, c'est pas si mal ce que fait le gouvernement actuel, non ? Allez, bisous, j'ai du bonheur à inflger à mes futurs employés ;-)" },
  { username: 'LBA', message: "Tu as été mon premier manager du temps de BA. C'est avec toi que je suis passé Sénior. Un très grand merci à toi et plein de bonnes choses pour la suite." },
  { username: 'LBO', message: "Merci pour ton intervention sur Pix. On a enrichit pas mal de trucs, mais on esrt parti d'une bonne base. Bonne chance sur Thalès." },
  { username: 'LCI', message: "Tu seras à jamais l'une de mes sources d'inspiration en termes de direction d'une société qui se veut humaine. C'est fou tout ce que tu as fait d'OCTO et ce que tu continues de faire pour les Octos. #chapeau #respect PS : merci de m'avoir fait confiance en tant que leader de tribu et pour Tout." },
  { username: 'LCH', message: "D'où t'as 2 'H' successifs dans ton nom de famille ?! Éclates-toi bien sur EISMO. Et oublie pas que je suis l'un des pères fondateurs de la pôme d'OCTO et que je serais toujours plus fort que toi ;-)" },
  { username: 'LDA', message: "Viens, on prend le pari : dans 15 ans le Web a remplacé le natif ! ;-P" },
  { username: 'LDU', message: "\"Pfff, c'est nul les départs.\" ™ Ah ! ah ! cette fois je l'ai dit avant toi ^^" },
  { username: 'LEB', message: "1 an déjà chez OCTO. Ça passe vite. J'espère que tu t'éclates et que ça va durer." },
  { username: 'LEE', message: "Toi tu fais fort avec ton trigramme qui est directement ton nom de famille. Crane pas trop, hein ;-)" },
  { username: 'LEF', message: "Il paraît que tu ne ressembles pas du tout à ta photo de profil et que tu fais beaucoup moins daron en vrai ^^" },
  { username: 'LIG', message: "Il va falloir apprendre à cadrer parce que pour les copains qui attendent le baby, c'est parfois long ;-)" },
  { username: 'LJA', message: "Rappel : tu peux changer de tribu à tout moment. Surtout si c'est pour aller chez WEBF :-p" },
  { username: 'LLE', message: "J'avais vraiment kiffé notre intervention conjointe (avec PBM et JTE) chez ERDF. Bonne continuation." },
  { username: 'LSK', message: "À 1 lettre près, et t'avais le même blaze qu'un ex-homme politique à la réputation sulfureuse. Comme quoi, à quoi ça tient la chance..." },
  { username: 'LOU', message: "Si t'avais été dans mon équipe, j'aurais renommé ton trigramme en LOU ; c'est d'ailleurs ce que j'ai fait." },
  { username: 'LTH', message: "Si t'avais été dans mon équipe, j'aurais renommé ton trigramme en LOU ; c'est d'ailleurs ce que j'ai fait." },
  { username: 'LYB', message: "Gros bisous Lynda. Merci pour ton aide pour toutes les demandes des Octos et des petites tracasseries du quotidien qui passent sans soucis grâce à toi." },
  { username: 'MAC', message: "Merci pour le coup de main pour la rétro WEBF de fin d'année. Qui sait, un jour peut-être nos chemins se recroiseront et j'aurais l'opportunité de travailler avec le Grand Marc Cherfi." },
  { username: 'MAH', message: "C'est à chaque fois trop cool de te croiser et papoter avec toi. T'as toujours le sourire, ça fait trop du bien. J'espère qu'on se recroisera. Bisous :-)" },
  { username: 'MAK', message: "Tu seras bientôt l'OCTO avec le plus de badges des différentes tribus par lesquelles il est passé. Un peu le \"Frédéric Dehu\" des tribus. L'un des inventeurs du Klub Sosie. Vous n'acceptez pas les membres postumes par hasard ? Bonne chance dans ta prochaine tribu." },
  { username: 'MAT', message: "Merci pour les discussions enrichissantes qu'on a pu avoir, surtout au 50. Bonne continuation." },
  { username: 'MAX', message: "Tu es l'un des IA avec qui j'ai le plus de plaisir et de confiance à bosser. Bravo pour ta résilience du temps de la Ligue Delivery. Et pourtant c'était pas tous les lundis faciles. Mais t'as toujours gardé le sourire et t'as continué de venir. #respect" },
  { username: 'MAZ', message: "Oh put*** ! Je n'ai jamais répondu à ton mail à mon retour de congés ! #désolé" },
  { username: 'MBE', message: "Tu es une source d'inspiration et l'un de mes modèles parmi les leaders de tribus. PS : mes amitiés à François. Tu pourras lui dire que la tribu est entre de bonnes mains : celles de Pierrette, Xavier et Clément :-) PS (bis) : félicitations pour ton futur heureux évènement, c'est trop cool !!!" },
  { username: 'MBI', message: "Bon courage et bonne chance pour la suite d'OCAC :-)" },
  { username: 'MBO', message: "Rappel : tu peux changer de tribu à tout moment. Surtout si c'est pour aller chez WEBF :-p" },
  { username: 'MDM', message: "Hola ! Bonne continuation chez UX. ++" },
  { username: 'MEA', message: "Coule pas !" },
  { username: 'MEB', message: "Définitivement pas le bon trigramme. En tout cas, pas celui de mon univers :-P" },
  { username: 'MEL', message: "T'es une pépite ! Un diamant. Une pépite de diamant. Qui n'a même pas besoin d'être beaucoup polie pour envoyer du lourd. C'est impressionnant ! PS : je suis trop heureux de t'avoir sur Pix <3 <3 <3" },
  { username: 'MEG', message: "Tu viens de m'éclater au baby ou je rêve ?!" },
  { username: 'MEH', message: "J'espère que ça se passe bien à la BNP. Bonne continuation ;-)" },
  { username: 'MEM', message: "On a fait seulement un début d'avant-vente ensemble, mais c'était cool. Bonne route ;-)" },
  { username: 'MFE', message: "Merci pour tout ce que tu as fait pour Pix et moi depuis 1 an. J'espère continuer à t'embêter pendant encore longtemps :-D" },
  { username: 'MGL', message: "Le sniper. Bonne chance pour la suite." },
  { username: 'MGU', message: "T'es trop folle. Je kiffe. Bisous Marina." },
  { username: 'MKI', message: "Alors, ça se passe bien ta nouvelle vie au Maroc ?" },
  { username: 'MLG', message: "Je me rappelle notre dej lors d'une journée manager. Bonne continuation Matthieu :-)" },
  { username: 'MLN', message: "Bonne chance et longue vie à l'offre 'Patient Centric'. Bisous "},
  { username: 'MMD', message: "Le boss du Service Public. Gardes la pêche !" },
  { username: 'MRA', message: "Je me rappelle la fois où on s'est retrouvé à la même table pour déjeuner. Bonne route Marine :-)" },
  { username: 'MTR', message: "Bonne route globe-trotter ;-)" },
  { username: 'MWA', message: "Je continuerai de suivre assidûment Bloculus" },
  { username: 'NAT', message: "Merci pour tout ce que tu fait pour OCTO, en particulier sur le volet \"stress\". C'est hyper impressionnant. Merci pour la patience que tu as eu à mon égard et pour ton aide pour quitter OCTO le plus proprement et dans les meilleures conditions." },
  { username: 'NBR', message: "T'as un énorme potentiel. Désolé de ne pas t'avoir aidé plus sur Pépite. À bientôt" },
  { username: 'NCA', message: "Le meilleur. Et pas qu'au baby. Tu défonces tout Nico. Au propre comme au (dé-)figuré. C'était un plaisir de bosser avec toi. Et je ne dis pas ça juste parce que t'as des muscles qui font le double des miens ^^" },
  { username: 'NCR', message: "La plus grosse arnaque du Web front-end ! Non, je déconne. Mais quand même, t'aurais au moins pu passer 6 mois chez nous... Bonne chance au Canada :-)" },
  { username: 'NDC', message: "On est d'accord, DDD ça ne rime à rien. Clean Architecture et Architecture Hexagonale idem. Non, je déconne. Passer une heure au détour d'un café ou d'un dej non planifié va beaucoup me manquer. #JeSuisNelson" },
  { username: 'NFO', message: "Je ne pense recroiser jamais quelqu'un maîtrisant Jira comme toi. #respect" },
  { username: 'NGR', message: "LA Maman de l'USI. What ?! ton manager c'est FHI ??? T'as décidément trop la classe #EtoilesPleinLesYeux" },
  { username: 'NIL', message: "Merci Nico pour tout ce que tu apportes à OCTO. T'es un super mec, simple, généreux, courageux, humain. J'ai adoré les échanges qu'on a eu. Bonne continuation." },
  { username: 'NVO', message: "C'était cool de discuter avec toi à tes débuts, au 50. Bonne continuation. PS : désolé pour toutes les fois où j'ai écorché ton prénom ^^" },
  { username: 'OCP', message: "Ahhhh ! Me pardonneras-tu un jour tous ces points RH que j'ai annulé au dernier moment..." },
  { username: 'OLR', message: "J'apprends trop de choses à chaque fois que je te vois. J'aurais dû songer à encore plus t'embêter, du coup ;-p" },
  { username: 'OLW'	, message: 	"ésolé, mais ça me fait toujours un petit quelque chose quand je vois un \"trigramme à 4 lettres\"... :'-(" },
  { username: 'ORO', message: "C'était bien quand tu étais là. Bisous pour la suite ;-)" },
  { username: 'OUM', message: "Le mec avec le trigramme le plus mal approprié ! Un jour tu regretteras de ne pas t'être mis à Ember avant !!! Bon courage pour la suite, et dépêches-toi de prendre encore plus de responsabilités. Tout le monde n'attend que ça ^^" },
  { username: 'PBE', message: "Tu es une personne formidable et j'ai toute confiance qu'avec toi à sa tête, la tribu WEBF va tout exploser dans les semaines, années et mois à venir. Je suis très fier d'avoir été ton manager ces quelques mois et j'espère t'avoir aidé à t'épanouir autant qu'il était possible. Continues de penser aux autres, c'est ta plus grande force, mais penses aussi à toi. Charité bien ordonnée commence par soi (parfois) ;-) Encore un énorme merci pour toutes nos merveilleuses discussions. Je te souhaite plein de bonheurs pour la suite, sur tous les plans. PS : Vicky est trop mignonne dans sa cape de bain ! Définitivement une excellente surprise (merci). Et utile. Bisous bisous <3" },
  { username: 'PBM', message: "Merci de m'avoir embarqué lors du lab ERDF. C'était intense, dans tous les sens du terme. À une prochaine." },
  { username: 'PFY', message: "J'aurais trop aimé faire une mission avec toi en DeMa. On se voit dans le tur-fu." },
  { username: 'PKN', message: "Un concurrent de GUE. Attention, il a pris une longueur (de cheveux) d'avance ! Bonne continuation." },
  { username: 'PNI', message: "The best Homo ever ! Je te souhaite plus que le meilleur dans ton rôle de nouveau DSI. Bisous" },
  { username: 'PPR', message: "J'ai adoré t'écouter (j'avais pas le niveau pour discuter) même si après je coup, je ne suis pas sûr de tout me rappeler, ni d'avoir tout comris ;-)" },
  { username: 'PSO', message: "T'es l'un des premiers Octos avec qui j'ai travaillé (sur SwissLife). Je te souhaite le meilleur pour la suite." },
  { username: 'PTR', message: "J'espère que ton voyage aux quatre coins du monde se passe bien. Encore bravo pour le JobBoard. ++" },
  { username: 'PYN', message: "Sur ta photo de profil AskBob, on dirait le garçon qui a illustré mon enfance sur les barres Kinder." },
  { username: 'RAH', message: "Bon courage pour la suite ;-)" },
  { username: 'RBO', message: "Il paraît que ça se passe bien pour toi sur ExplorImmo. Ça me fait trop plaisir pour toi. Bisous calin bisous calin" },
  { username: 'RDV', message: "Avec tout ce que me raconte ASA, j'ai trop envie de travailler avec toi. Peut-être prochainement sur Pix ? ++" },
  { username: 'ROQ', message: "Ah la la ! Je ne serais pas là pour voir jusqu'à quel point t'es devenu puissant… T'as un potentiel énorme, mais ce sont surtout tes qualités humaines et d'organisateur que je retiendrai. Gros bissous. Oublies pas de défoncer le terrain de RG pour moi. De toute façon, \"l'année prochaine ils vont tout refaire\" (again and again)." },
  { username: 'RVA', message: "J'espère que je t'ai suffisamment aidé chaque fois que tu m'as sollicité. Bonne route." },
  { username: 'SAB', message: "J'ai trouvé que tu avais bien géré la journée leader de tribu du début de l'année. En tout cas c'était un plaisir de faire ta connaissance à ce moment là. Salut ;-)" },
  { username: 'SAF', message: "Merci pour ta bonne humeur et ton sourire en toutes circonstances ;-)" },
  { username: 'SAM', message: "Nos longues discussions métaphysiques vont trop me manquer ! Les 2 heures de trajet en bus dans la pampa du Sénégal ou du Maroc passent tellement plus vite à débattre de tout, de rien mais surtout trop loin avec toi. Bisous." },
  { username: 'SAR', message: "Bonne chance à l'ANEF :-)" },
  { username: 'SBI', message: "SBIiiiiiiiiii ! Toi, tu mérites plein de bisous. Tu es trop forte ! Tu m'as tellement de fois sauvé et simplifier la vie. Ma femme te passe le bonjour ;-)" },
  { username: 'SBO', message: "Je pense que tu as un petit grain. Mais c'est cool ^^" },
  { username: 'SBU', message: "Le mec avec la plus longue description AskBob et le plus grand nombre d'articles publiés. Good job" },
  { username: 'SCA', message: "J'étais aux toutes premières loges de la danse de ce midi. Je connais un très bon psychatre, tu sais. Non, en vrai, c'était couillu. Bravo pour ton crin, euh, ton cran !" },
  { username: 'SCH', message: "Tu te rappelles quand je t'ai déposé après le Maroc (ou le Sénagal, je ne me rappelle jamais dans quel ordre) ? Bref, bonne continuation (avec la SGCIB, toujours) voisin ;-)" },
  { username: 'SDL', message: "J'aurais aimé mieux te connaître. Pour cela, il aurait fallu que je passe plus souvent à la COM. Tant pis. Bonne continuation quand même et bisous ;-)" },
  { username: 'SED', message: "Encore un avec un nom de commande Unix. La classe ! On peut dire que tu en as \"Dubol\". PS : j'assume le fait de ne pas être le premier à te la faire ^^" },
  { username: 'SFA', message: "Pour moi, tu es l'incarnation ultime du consultant fonctionnel sénior. T'es une putain de pointure, mec. En plus t'es hyper cool. Un exemple pour des générations d'Octos. Big up !" },
  { username: 'SHA', message: "Il paraît que ce n'est pas toujours facile de te comprendre, car tu es dure à déchiffrer… #MaMeilleureVanne Bisous (même si on ne se connaît pas, c'est pour le principe)" },
  { username: 'SIG', message: "Tu es l'une des personnes chez OCTO avec un intitulé de poste unique. Respect ;-)" },
  { username: 'SIK', message: "Je t'aime fort comMMMMEEEE CAAAAAA ! (avec des grands grands bras ouverts). Bisous ma Siti. Tu es une super personne. Merci pour tout." },
  { username: 'SKN', message: "Alors comme ça Môssieur décide de s'en aller 9 mois seulement après être arrivé et avoir tout déchiré sur Europ Assistance, soi-disant pour suivre son amoureuse. À cause de toi, j'ai BRO qui déprime et qui nous saoûle à ressasser le passé. Non, sérieux, j'espère que tu t'es éclaté tout ce temps et je te souhaite tout le meilleur pour le tur-fu. Bisous baveux." },
  { username: 'SLL', message: "Le beau gosse de service ! En plus t'es gentil et hyper compétent. Si je ne t'appréciais pas, je te jure que je te détesterais à un point, t'imagines même pas !" },
  { username: 'SLU', message: "On n'a pas eu l'occasion de travailler ensemble, mais je suis sûr qu'on aurait fait une super équipe. Quoiqu'il en soit, bonne continuation et à un de ces jours peut-être ;-)" },
  { username: 'SMA', message: "Il me reste encore plein de notes de frais à te transmettre… mais surtout plein de bisous et de câlins à te faire. Merci pour tout ce que tu fais pour OCTO depuis tant d'années. J'espère que tu vas être gâtée à la plénière." },
  { username: 'SMI', message: "J'espère que la formation JS lors du cursus Skool a été à la hauteur de celles que tu donnais chez Simplon. Bonne continuation :-)" },
  { username: 'SOM', message: "Gardes ton sourire et ton énergie, c'est trop agréable. Surtout sur certains plateaux de certaines banques un peu moroses :-D #Wa!" },
  { username: 'SPR', message: "C'était cool de prendre des cafés avec toi, et toujours hyper instructif. Bonne chance pour la suite :-)" },
  { username: 'SRE', message: "Encore merci pour l'aide que tu nous as apportée sur la formation JS :-)" },
  { username: 'SRO', message: "Tes Cafés Craft sont énormes ! J'adore discuter avec toi. J'espère avoir l'occasion de travailler ensemble dans le futur. Bonne route ;-)" },
  { username: 'STM', message: "Bravo pour ce que tu es parvenu à faire d'OCAC. J'ai apprécié chacune de nos discussions. Désolé si parfois j'ai manqué de réactivité. Bisous ;-)" },
  { username: 'STP', message: "T'es un Tech Lead et un leader de tribu référent à mes yeux chez OCTO. La MOB a de la chance de t'avoir à sa tête. Bonne continuation. #RMWRockStar" },
  { username: 'SYG', message: "Merci pour la confiance que tu m'as accordée et les (belles) missions que tu m'as proposées. T'es un frère. Bisous. PS : les cheveux longs, non ;-)" },
  { username: 'TBR', message: "Un grand bravo à ce que tu as fait sur RMW. Ce n'était pas gagné de prendre la relève du grand FMI. Tschuss !" },
  { username: 'TDA', message: "Je n'oublierais jamais comment on a tout écrasé au Koezio avec AJU ~ http://mission.koezio.co/fr/photos/3/30-06-2017/17:00" },
  { username: 'TGE', message: "On se refait une mission quand tu veux ! Tu es l'un des Octos, à l'époque junior, qui m'avait le plus impressionné. Gardes ton énergie et ta joie de vivre, ça n'a pas de prix :-D" },
  { username: 'THC', message: "On se voit dans le tur-fu, là où tu sembles avoir le plus ta place. Ciao ;-)" },
  { username: 'TLU', message: "T'as de la chance d'avoir Mr JVI en manager. Profites-en bien !" },
  { username: 'TPA', message: "Le mec qui laisse des fans partout où il passe. #chapeau" },
  { username: 'TPE', message: "Cynique, mais drôle. J'aime." },
  { username: 'TTO', message: "J'ai vraiment apprécié les échanges qu'on a eu sur Europ Assistance. T'es un super DeMa. Bonne continuation ;-)" },
  { username: 'TVI', message: "Trop de souvenirs sur Allianz avec toi. Les schémas d'un code inextricable, ta vélocité fabuleuse de rédaction de slides, ma panique lors de mon premier entretien en tant que lead, où j'étais mort au bout de 2mn et où tu m'as sauvé la vie, malgré tes congés, la restitution qui est passé comme une lettre à la poste. J'ai vraiment eu de la chance de t'avoir comme mentor pour ma première mission de conseil. T'es un mec en or. Bonne continuation et encore merci pour tout <3" },
  { username: 'TWI', message: "L'inventeur et auteur de Cafe-Craft.fr (http://www.cafe-craft.fr) ! Pix serait complètement différent si tu n'avais pas été là au tout début. Ou ne serait pas, tout simplement. Je sais que je suis souvent chiant et que je me fais souvent l'avocat du diable, mais c'est mon côté SALT ;-)" },
  { username: 'URA', message: "Un transfuge d'Accenture. On ne se serait pas aussi déjà croisé dans des meet-ups ? Bonne route au sein d'OCTO ;-)" },
  { username: 'VAB', message: "Le temps où tu étais le premier sourire de tout un chacun à l'accueil chez OCTO me manque. Je ne peux que te souhaiter qu'une chose : \"Gardes la pêche !\" ;-)" },
  { username: 'VEN', message: "Désolé de gâcher ta soirée jeux de sociétés. Merci de m'avoir repris sur @tech l'autre fois. Et puis t'as NDC en manager, tu dois forcément être un mec bien X-D" },
  { username: 'VGU', message: "Le mec le plus ouf de tout OCTO. Comme la VR, on se demande ce que c'est que cet ovni et puis rapidement ça nous paraît indispensable. On devrait tous avoir un VGU dans sa team ! PS : 29" },
  { username: 'VID', message: "T'as une super personnalité. Bonne chance avec La Poste !" },
  { username: 'VMI', message: "Il paraît que tu déchires en Ops. J'ai pas eu la chance de le voir de mes yeux. Par contre j'ai pu constater à quel point tu m'as déchiré au baby ;-)" },
  { username: 'VTO', message: "Un super ingénieur d'affaire. J'ai beaucoup aimé chaque fois qu'on a eu à travailler ou échanger ensemble. Merci pour les consultants." },
  { username: 'VWA', message: "J'ai trop kiffé la discussion qu'on a eu ensemble à ton arrivée. Et j'adore tes tatouages." },
  { username: 'WAL', message: "On n'a pas travaillé ensemble mais j'ai toujours entendu beaucoup de bien de toi :-)" },
  { username: 'WBO', message: "Merci pour ta patience et ton écoute à mon égard pour la mission Portail V2 avec XJU, MEB et CDP." },
  { username: 'WON', message: "On est arrivé quasi-ensemble à OCTO il y a presque 5 ans. Que de chemin parcouru ! Surtout pour toi ;-) J'espère que tu t'éclates en Australie et je te souhaite le meilleur pour l'avenir, sur le plan pro et perso. #amitiés" },
  { username: 'WWO', message: "T'es un super mec et j'aurais kiffé faire une mission avec toi. Bonne chance avec \"ta\" Skool :-)" },
  { username: 'XJU', message: "Merci d'avoir pris le risque d'être mon tout premier managé (et d'avoir continué). Je suis extrèmement fier de toi et de ton parcours. Je te souhaite le meilleur pour la suite et un bon co-leading de tribu." },
  { username: 'XMC', message: "Bonne chance et bon courage avec Virtuoz." },
  { username: 'YAB', message: "On ne s'est vu que lors de formations ou de journées managers, mais à chauqe fois j'ai apprécié ton humilité et les échanges qu'on a pu avoir. Bonne chance poour la suite." },
  { username: 'YAH', message: "On joue l'un contre l'autre quand tu veux !" },
  { username: 'YDE', message: "Mon premier parrainé. Je me mettais la pression pour bien t'accueillir. Je me dis que j'ai réussi. Dommage qu'on n'ait pas eu l'occasion de travailler ensemble." },
  { username: 'YOU', message: "On n'a pas eu le temps de travailler ensemble mais tu as l'air cool. Et je kiffe ton trigramme." }
];

export default Component.extend({

  username: null,

  message: computed('username', function() {
    const username = this.get('username');

    if (!username || username.length < 3) {
      return null;
    }

    if (username.length > 4) {
      return `What ?! Un username de ${username.length} caractères !?! Tu te paierais pas ma tête par hasard ? Non, parce qu'au cas où tu ne le saurais pas encore, je suis un espèce de gros psychopathe qui connaît ton adresse IP !`
    }

    const matchingItem = messages.find((item) => username.toLowerCase() === item.username.toLowerCase());
    if (matchingItem) {
      return matchingItem.message;
    }
    return "Malheureusement, nous n'a pas eu l'occasion de travailler ensemble. En compensation voici une jolie petite 🦄 :-)";
  })

});
